import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import LinkMenu from "@/components/LinkMenu";
import localFont from 'next/font/local'
import Link from "next/link";
import Footer from "@/components/Footer";

const elaineKinandhita = localFont({
  src: './elainekinandhita.regular.ttf',
  display: 'swap'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={elaineKinandhita.className + " bg-purple-100"}>
        <nav className="w-screen max-w-full flex justify-center sm:justify-end items-center sm:px-20 pt-8 pb-2">
          <LinkMenu/>
        </nav>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
